### PR TITLE
Use `mktemp` instead of `tempdir`

### LINKED ISSUE #427: Makefile: `tempfile` is debian-specific
And not available on macOS. An alternative which works for both is `mktemp`.

### PR DESCRIPTION
**Pull request by pat-s**
fix #427 

This fixes the makefile rule for me on macOS and it also (still) works on Linux.

### CODE REVIEW

**Comment by leg100** [comment]
Doesn't work for me:

```bash
> make install-latest-release 
{ \
set -ex ;\
ZIP_FILE=$(mktemp -t otf) ;\
RELEASE_URL=$(curl -s https://api.github.com/repos/leg100/otf/releases/latest | jq -r '.assets[] | select(.name | test("otfd_.*_linux_amd64.zip$")) | .browser_download_url') ;\
curl -Lo $ZIP_FILE $RELEASE_URL ;\
unzip -o -d /home/louis/go/bin $ZIP_FILE otfd ;\
}
+ mktemp -t otf
mktemp: too few X's in template ‘otf’
+ ZIP_FILE=
make: *** [Makefile:54: install-latest-release] Error 1

```

**Comment by pat-s** [comment]
Interesting. Gave this a try on macos and Ubuntu. What distro are you using?

**Comment by leg100** [comment]
Ubuntu 22.10

**Comment by pat-s** [comment]
@leg100 This should also work. Double-checked on macOS and Ubuntu 22.04

**Pull request merged**
