### PR TITLE
wip oidc research

### PR DESCRIPTION
**Pull request by robbert229**
Opening this up for observability and to ask for some feedback from @leg100 on general direction.
This PR takes a swing at #360, and also #342 since one of the main oidc providers supports gitea (dex)

### CODE REVIEW

**Comment by robbert229** [comment]
Overall I think I have things kind of working, though the permission management side is a bit meh. I was doing local dev using [dex](https://github.com/dexidp/dex) instead of directly talking to something like github via oidc. 

image
image
image

**Comment by leg100** [comment]
@robbert229 Looks intriguing! Forgive my OIDC ignorance: how does the issuer populate the organizational policy claim?

**Comment by robbert229** [comment]
> @robbert229 Looks intriguing! Forgive my OIDC ignorance: how does the issuer populate the organizational policy claim?

It doesn't. To get some permission management I had to add a cli option. I am not super happy with it, but generally tools integrating via oidc need some sort of external policy related configuration.

```
--oidc-organization-policies="SomeCoolOrg,admins,,,,"
--oidc-organization-policies="SomeOtherOrg,admins,admins,admins,admins,admins"
```

Some prior art might be: https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/

**Comment by leg100** [comment]
OK I think I get it. You're using the groups specified in the OIDC `groups` claim as keys with which to lookup a corresponding organization and team provided via a CLI provided hash-map.

It's a creative solution to this difficult problem: OIDC deals with one dimension of authorization (groups), whereas OTF deals with two (orgs and teams). I'm assuming here that we're restricted to relying upon on the non-standard OIDC `groups` JSON array and not a JSON object which would get around this problem.

When making design decisions in OTF I often follow what TFC/E does. Now, they both use SAML rather than OIDC but they perform a similar mapping of team membership. TFC and TFE handle it slightly differently it appears.

In TFC, SAML is configured per-organization, thereby working around this problem. The SAML token contains a `memberOf` assertion that contains the groups and these are mapped to teams in the organization.

Whereas in TFE, SAML is configured for the instance and so it does face this problem. What does it do? Well, from the docs:

> Note that team names are unique across an organization but not necessarily unique across a whole Terraform Enterprise instance. If a user is a member of multiple organizations, their SAML assertion might add them to similarly-named teams in each organization. Keep this in mind when naming your teams.

https://developer.hashicorp.com/terraform/enterprise/saml/team-membership

So it ignores the organizations and blindly maps the SAML group to team names across all organizations.

I'm not sure which is the best approach.

**Comment by robbert229** [comment]
> It's a creative solution to this difficult problem: OIDC deals with one dimension of authorization (groups), whereas OTF deals with two (orgs and teams). I'm assuming here that we're restricted to relying upon on the non-standard but common-place OIDC groups JSON array and not a JSON object which would get around this problem.

Exactly.

> When making design decisions in OTF I often follow what TFC/E does. Now, they both use SAML rather than OIDC but they perform a similar mapping of team membership. TFC and TFE handle it slightly differently it appears.

sounds like I should have dug around in TCF/E docs before I started poking at this lol. I think I have a bit better of a handle on things now. My initial pass got muddied from a lack of familiarity with the codebase. I think I might have a bit better of an idea on things now.

I dug out this snippet from their docs:

> You can enable automatic membership in the owners team (on a per-organization basis) by explicitly specifying an alias (role ID) for it. On your organization settings page, click "Teams" and then click the owners team. If SAML is enabled, there will be a "SAML Role ID" field. Enter a legal team name as an ID and click "Save." The ID can be "owners," but it cannot conflict with any other team name.

It sounds like there is some manually created teams, and then the saml role id is used to map groups to teams. How about doing something like this:

```
--oidc-policies="SomeCoolOrg, admins, team:owners" \
--oidc-policies="SomeCoolOrg, my-org-developers, team:developers" \
--oidc-policies="SomeOtherOrg, admins, team:owners" \
--oidc-policies="SomeOtherOrg, my-org-developers, team:developers" \
```

We specify what organization the mapping is for, then the group role (equivalent to the saml role id that TFC/E uses), and then the team that we want to map things to.

**Comment by leg100** [comment]
I think you should hold off adding AuthZ, i.e. leave out group/team sync altogether, and restrict this PR to AuthN, i.e. the bulk of the OIDC work you've done already.

This won't be very useful as it stands. You would have to create teams and orgs manually, and add the user to teams manually. And even then, the way the authenticator works currently, when the user signs in, the authenticator would remove the user from any teams they were manually added to.

But I intend to make synchronisation configurable. Then the manual changes above would survive a login.

We can then look again at how we do group sync for OIDC.

**Comment by robbert229** [comment]
This makes sense, and I agree regarding holding off on the authz bits.

What kind of time frame were you thinking regarding the manual syncing, and is there anything I could do to help?

**Comment by leg100** [comment]
> What kind of time frame were you thinking regarding the manual syncing, and is there anything I could do to help?

It shouldn't take long, within a couple of days I should think. If you like, you could have a stab.

I'm considering changing the _auto-provisioning_. At present, when a user signs in via github/gitlab, OTF looks up their organizations and teams in github/gitlab and creates them in OTF too if they don't already exist. It also creates a personal organization with them as an owner. But I'm thinking that can be simplified down to only creating the personal organization, and dropping the auto-provisioning of other organiations/teams. Users would instead be responsible for manually adding organizations and teams in OTF.  Let me know what you think of this.

_Auto-synchronisation_ of team membership would remain, but it would only synchronise with teams that already exist in OTF. And like I said, I'll be adding an option to turn this off.

**Comment by robbert229** [comment]
> It shouldn't take long, within a couple of days I should think. If you like, you could have a stab.

Thanks, but I will defer to you. I am still poking around the codebase and trying to wrap my head around some things, and don't really know that side of the codebase yet. Thanks for the offer though.

> I'm considering changing the auto-provisioning. At present, when a user signs in via github/gitlab, OTF looks up their organizations and teams in github/gitlab and creates them in OTF too if they don't already exist. It also creates a personal organization with them as an owner. But I'm thinking that can be simplified down to only creating the personal organization, and dropping the auto-provisioning of other organiations/teams. Users would instead be responsible for manually adding organizations and teams in OTF. Let me know what you think of this.

I think that overall this makes sense, and a I like it. 

I think with manual provisioning of teams it would be quite nice to be able to lock down org, and team creation to only the admin, then I could probably build a otf terraform provider to gitops my otf configuration.

**Comment by leg100** [comment]
> I think with manual provisioning of teams it would be quite nice to be able to lock down org, and team creation to only the admin, then I could probably build a otf terraform provider to gitops my otf configuration.

You can use the [tfe provider](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs) for many actions. Support is patchy, I need to create a compatibility matrix showing what can and can't be done. For example you can manage organizations, workspaces, and workspace variables via the provider, but users and teams aren't fully supported yet. It depends  on where I've exposed services via `JSON:API`, the protocol that TFC/E uses and what `terraform` uses to trigger remote runs.

**Comment by leg100** [comment]
Looks good @robbert229 , let me know when it's ready for review (I see it is in draft status).

**Comment by leg100** [comment]
@robbert229 I've migrated the docs. You'll want to move the section you've written to a dedicated file in `./docs/auth/providers`, and link to it from `./docs/auth/index.md`.

**Comment by robbert229** [comment]
> Looks good @robbert229 , let me know when it's ready for review (I see it is in draft status).

The only thing left is some unit tests, I am planning on trying to wrap up the PR this evening. 

Thanks for the fyi on the docs.

**Comment by leg100** [comment]
> The only thing left is some unit tests, I am planning on trying to wrap up the PR this evening.

Shall I see what I can do? I can just merge it in and make any changes / add tests as necessary.

**Comment by leg100** [comment]
image

**Comment by leg100** [comment]
@robbert229 Hope you don't mind, I've finished this up with a few changes and some tests. Thanks for all your work on this.

**Pull request merged**
